### ISSUE TITLE
Violentmonkey shows errors in match patterns

### ISSUE THREAD

**Issue by dembeck** [gserafini/fix-gmail-email-search-userscript#5]
When adding the script to **Violentmonkey v2.13.3** it says that there are errors with the match patterns. 

I checked the browser console to see if it was causing any issues and noticed that it was complaining about the match patterns, as well as a TypeError and an issue with TrustedHTML.

---

The good news is that the script is working correctly, adding the search icon, and performing a search when clicked in Gmail. Very helpful!

I did want to make you aware of the errors, but I am not too concerned about them.

## Violentmonkey Errors:

```
Bad pattern: missing "://" in *gmail.com/*
Bad pattern: missing "://" in *mail.google.com/*
Bad pattern: missing "://" in *contacts.google.com/widget/hovercard/*
```

## Violentmonkey Screenshots:

![image](https://user-images.githubusercontent.com/9568447/203223433-2b394e8f-d30d-45aa-8263-b2483c396479.png)

![image](https://user-images.githubusercontent.com/9568447/203223403-5532f490-adb1-433a-8f47-4c412eea1c1a.png)

## Browser Console Logs:

This is a screenshot of the console and the text of the log.

![image](https://user-images.githubusercontent.com/9568447/203227556-64d09d2e-751a-4e10-bde1-b9edeb3c12ea.png)

```log
21:04:05.818 injected.js:1 
        
       Bad pattern: missing "://" in *gmail.com/* - chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/Fix%20Gmail%20Email%20Search.user.js#186
Bad pattern: missing "://" in *mail.google.com/* - chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/Fix%20Gmail%20Email%20Search.user.js#186
Bad pattern: missing "://" in *contacts.google.com/widget/hovercard/* - chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/Fix%20Gmail%20Email%20Search.user.js#186
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
21:04:10.245 This document requires 'TrustedHTML' assignment.
21:04:10.245 This document requires 'TrustedHTML' assignment.
21:04:10.245 This document requires 'TrustedHTML' assignment.
21:04:10.245 This document requires 'TrustedHTML' assignment.
21:04:10.245 This document requires 'TrustedHTML' assignment.
21:04:08.881 Fix Gmail Email Search.user.js:2 
        
       This document requires 'TrustedHTML' assignment.
(anonymous) @ Fix Gmail Email Search.user.js:2
ce @ Fix Gmail Email Search.user.js:2
se.setDocument @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
window.VMingl7memykh9rjz3zc @ Fix Gmail Email Search.user.js:112
a @ injected-web.js:1
Lt @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ Fix Gmail Email Search.user.js:1
ut @ injected.js:1
ft @ injected.js:1
await in ft (async)
pt @ injected.js:1
dt @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
Ie @ injected.js:1
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
21:04:08.885 Fix Gmail Email Search.user.js:2 
        
       This document requires 'TrustedHTML' assignment.
(anonymous) @ Fix Gmail Email Search.user.js:2
ce @ Fix Gmail Email Search.user.js:2
se.setDocument @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
window.VMingl7memykh9rjz3zc @ Fix Gmail Email Search.user.js:112
a @ injected-web.js:1
Lt @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ Fix Gmail Email Search.user.js:1
ut @ injected.js:1
ft @ injected.js:1
await in ft (async)
pt @ injected.js:1
dt @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
Ie @ injected.js:1
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
21:04:08.888 Fix Gmail Email Search.user.js:2 
        
       This document requires 'TrustedHTML' assignment.
(anonymous) @ Fix Gmail Email Search.user.js:2
ce @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
window.VMingl7memykh9rjz3zc @ Fix Gmail Email Search.user.js:112
a @ injected-web.js:1
Lt @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ Fix Gmail Email Search.user.js:1
ut @ injected.js:1
ft @ injected.js:1
await in ft (async)
pt @ injected.js:1
dt @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
Ie @ injected.js:1
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
21:04:08.891 Fix Gmail Email Search.user.js:2 
        
       This document requires 'TrustedHTML' assignment.
(anonymous) @ Fix Gmail Email Search.user.js:2
ce @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
window.VMingl7memykh9rjz3zc @ Fix Gmail Email Search.user.js:112
a @ injected-web.js:1
Lt @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ Fix Gmail Email Search.user.js:1
ut @ injected.js:1
ft @ injected.js:1
await in ft (async)
pt @ injected.js:1
dt @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
Ie @ injected.js:1
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
21:04:08.902 Fix Gmail Email Search.user.js:2 
        
       This document requires 'TrustedHTML' assignment.
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
window.VMingl7memykh9rjz3zc @ Fix Gmail Email Search.user.js:112
a @ injected-web.js:1
Lt @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ Fix Gmail Email Search.user.js:1
ut @ injected.js:1
ft @ injected.js:1
await in ft (async)
pt @ injected.js:1
dt @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
Ie @ injected.js:1
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
21:04:08.989 Fix Gmail Email Search.user.js:2 
        
      
        
        
      
      
       
        
       Uncaught (in promise) TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at Fix Gmail Email Search.user.js:2:38037
    at Fix Gmail Email Search.user.js:2:220
    at Fix Gmail Email Search.user.js:2:225
    at window.VMingl7memykh9rjz3zc (Fix Gmail Email Search.user.js:112:7)
    at a (injected-web.js:1:16473)
    at Lt (injected-web.js:1:16548)
    at set (injected-web.js:1:16340)
    at Fix Gmail Email Search.user.js:1:28
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
(anonymous) @ Fix Gmail Email Search.user.js:2
window.VMingl7memykh9rjz3zc @ Fix Gmail Email Search.user.js:112
a @ injected-web.js:1
Lt @ injected-web.js:1
set @ injected-web.js:1
(anonymous) @ Fix Gmail Email Search.user.js:1
await in (anonymous) (async)
pt @ injected.js:1
dt @ injected.js:1
(anonymous) @ injected.js:1
await in (anonymous) (async)
(anonymous) @ injected.js:1
Ie @ injected.js:1
lt @ injected.js:1
qt @ injected.js:1
await in qt (async)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
```

**Comment by gserafini** [comment]
Just made improvements. Try the latest version 1.5 to see if that fixes things for you:
https://github.com/gserafini/fix-gmail-email-search-userscript/raw/master/fix_gmail_email_search.user.js
